#### 실제 데이터 2개 유사도 비교

In [1]:
import pandas as pd

origin_data1 = pd.read_csv('data/CT1st_Case1.csv', encoding='cp949')
origin_data2 = pd.read_csv('data/CT1st_Case2.csv', encoding='cp949')

columns = ["LD1 Temp", "LD2 Temp", "LD3 Temp", "Rx1 Temp", "Rx2 Temp", "S1 T(C)", "S2 T(C)", "S3 T(C)", "FR Mon"]
data1 = origin_data1[columns]
data2 = origin_data2[columns]

In [2]:
for col in columns:
    count = 0
    for i in range(0, len(data1)):
        if data1[col][i] == data2[col][i]:
            continue
        else:
            count += 1
    print(col, " : ", count)

LD1 Temp  :  0
LD2 Temp  :  0
LD3 Temp  :  0
Rx1 Temp  :  0
Rx2 Temp  :  0
S1 T(C)  :  1782
S2 T(C)  :  1782
S3 T(C)  :  1782
FR Mon  :  1782

In [3]:
sensor_column2 = ["LD_Bias_Av", "mPDdSr31", "mPDdSr32", "mPDdSr21", "T-rPDdSr31", "T-rPDdSr32", "T-rPDdSr21"]
data_sam2 = origin_data2[sensor_column2]
data_sel2 = data_sam2[data_sam2["LD_Bias_Av"] > 0]
data_sel2 = data_sel2[data_sel2["mPDdSr31"] > 0]
data_sel2 = data_sel2[data_sel2["mPDdSr32"] > 0]
data_sel2 = data_sel2[data_sel2["mPDdSr21"] > 0]

sensor_column1= ["LD_Bias_Av", "mPD1_dS", "mPD2_dS", "mPD3_dS", "T-rPD_L1dS", "T-rPD_L2dS", "T-rPD_L3dS"]
data_sam1 = origin_data1[sensor_column1]
data_sel1 = data_sam1[data_sam1["LD_Bias_Av"] > 0]
data_sel1 = data_sel1[data_sel1["mPD1_dS"] > 0]
data_sel1 = data_sel1[data_sel1["mPD2_dS"] > 0]
data_sel1 = data_sel1[data_sel1["mPD3_dS"] > 0]

data_sel2.columns = data_sel1.columns

print(len(data_sel2))
print(len(data_sel1))

178
178

In [4]:
data_sel1.head()

,LD_Bias_Av,mPD1_dS,mPD2_dS,mPD3_dS,T-rPD_L1dS,T-rPD_L2dS,T-rPD_L3dS
594,29.8,369.077591,699.430695,737.926338,1029.631130,571.574337,379.816130
854,29.8,367.442024,693.527321,743.185875,1027.924038,581.149380,388.256275
1114,29.8,368.491066,693.350899,745.508118,1036.984070,582.751564,392.600327
1374,29.8,368.095295,696.755569,741.955620,1033.064434,578.173870,389.834618
1634,29.8,372.591949,709.620796,742.232201,1041.280415,595.740826,389.896629

In [5]:
data_sel2.head()

,LD_Bias_Av,mPD1_dS,mPD2_dS,mPD3_dS,T-rPD_L1dS,T-rPD_L2dS,T-rPD_L3dS
594,29.8,1.999380,1.055039,1.895078,0.368886,0.664509,0.555125
854,29.8,2.022594,1.071603,1.887447,0.377709,0.668083,0.565362
1114,29.8,2.023138,1.075225,1.881595,0.378598,0.673701,0.561968
1374,29.8,2.015662,1.064872,1.892867,0.377358,0.674252,0.559669
1634,29.8,1.992078,1.045956,1.904552,0.374440,0.654474,0.572123

In [6]:
data_sel1 = data_sel1.reset_index(drop=True)
data_sel2 = data_sel2.reset_index(drop=True)

for col in sensor_column1:
    count = 0
    for i in range(0, len(data_sel1)):
        if data_sel1[col][i] == data_sel2[col][i]:
            continue
        else:
            count += 1
    
    print(col, " : ", count)

LD_Bias_Av  :  0
mPD1_dS  :  178
mPD2_dS  :  178
mPD3_dS  :  178
T-rPD_L1dS  :  178
T-rPD_L2dS  :  178
T-rPD_L3dS  :  178

In [7]:
data_sel1.head()

,LD_Bias_Av,mPD1_dS,mPD2_dS,mPD3_dS,T-rPD_L1dS,T-rPD_L2dS,T-rPD_L3dS
0,29.8,369.077591,699.430695,737.926338,1029.631130,571.574337,379.816130
1,29.8,367.442024,693.527321,743.185875,1027.924038,581.149380,388.256275
2,29.8,368.491066,693.350899,745.508118,1036.984070,582.751564,392.600327
3,29.8,368.095295,696.755569,741.955620,1033.064434,578.173870,389.834618
4,29.8,372.591949,709.620796,742.232201,1041.280415,595.740826,389.896629

In [8]:
data_sel2.head()

,LD_Bias_Av,mPD1_dS,mPD2_dS,mPD3_dS,T-rPD_L1dS,T-rPD_L2dS,T-rPD_L3dS
0,29.8,1.999380,1.055039,1.895078,0.368886,0.664509,0.555125
1,29.8,2.022594,1.071603,1.887447,0.377709,0.668083,0.565362
2,29.8,2.023138,1.075225,1.881595,0.378598,0.673701,0.561968
3,29.8,2.015662,1.064872,1.892867,0.377358,0.674252,0.559669
4,29.8,1.992078,1.045956,1.904552,0.374440,0.654474,0.572123